logging:
  level:
     org: 
         springframework:
            beans: debug
            context: debug
         hibernate:
            type:
               descriptor:
                  sql: trace #loging설정
      
spring:
  datasource:
    url: jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: jdeveloper29
    password: jdeveloper29
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode:  always
      schema-locations:
      #-user.ddl
      data-locations:
      - classpath:user-insert.sql
      